CREATE DATABASE realestate;

DROP TABLE House;
DROP TABLE Seller;
DROP TABLE PhoneNumber;
DROP TABLE Buyer;
DROP TABLE Agent;

USE realestate;
CREATE TABLE Seller(
	SSN VARCHAR(11),
	SName VARCHAR(30),
	Spouse VARCHAR(30),
	SPhoneNumber VARCHAR(11),
	CONSTRAINT SellerPK PRIMARY KEY (SSN) 
	);

CREATE TABLE Agent(
	AgentID INTEGER,
	AName VARCHAR(30),
	Office VARCHAR(30),
	CONSTRAINT AgentPK PRIMARY KEY (AgentID)
	);

CREATE TABLE House(
	HouseID INTEGER,
	SquareFeet INTEGER,
	StreetName VARCHAR(30),
	State CHAR(2),
	SellerSSN VARCHAR(11),
	AgentID INTEGER,
	Commission INTEGER,
	Price INTEGER,
	CONSTRAINT HousePK PRIMARY KEY (HouseID),
	CONSTRAINT SellerFK FOREIGN KEY (SellerSSN)
		REFERENCES Seller(SSN),
	CONSTRAINT AgentFK1 FOREIGN KEY (AgentID)
		REFERENCES Agent(AgentID)
	);

CREATE TABLE PhoneNumber(
	AgentID INTEGER,
	PPhoneNumber VARCHAR(11),
	CONSTRAINT PhoneNumberPK PRIMARY KEY (AgentID, PPhoneNumber),
	CONSTRAINT AgentFK2 FOREIGN KEY (AgentID)
		REFERENCES Agent(AgentID)
	);

CREATE TABLE Buyer(
	SSNb VARCHAR(11),
	BName VARCHAR(30),
	MinPrice INTEGER,
	MaxPrice INTEGER,
	BPhoneNumber VARCHAR(11),
	AgentID INTEGER,
	CONSTRAINT BuyerPK PRIMARY KEY (SSNb),
	CONSTRAINT AgentFK3 FOREIGN KEY (AgentID)
		REFERENCES Agent(AgentID)
	);